### ISSUE TITLE
Ethernal waiting

### ISSUE THREAD

**Issue by Vadim2S** [fgsect/magicfern#1]
I am try project with 4 reference and 1 candidate images. If candidate from same camera and dimension - all OK. If not - I am get following lines and ethernal (more than 30 minutes) waiting. No result at all.

"threads(saturation, noise extraction, intensity scale): 59328125
addition of the noise: 609375"

**Comment by HenrikAYT** [comment]
I can't reproduce the error right now, maybe you should add more information. However, if the candidate image from a different camera has different dimensions compared to the 4 reference images it makes no sense in a real life scenario to compare them because they obviously are from different camera sensors. Therefore, keep in mind to use the same dimensions for all candidate and reference images (best would be RAW images) but works also for compressed images.

**Comment by Vadim2S** [comment]
I am try resize candidate image - no luck.

I am use 4 3000*4000 original Panasonic LF-1 JPG images and Nikon D90 NEF(RAW)->Photoshop->JPG image

I am try another set of images later. If no luck again, I am attach they here.

**Comment by Vadim2S** [comment]
Hi! I am found stuck cause! If command line somewhat wrong i.e. candidate file not exist. There no error like 'file not found' but ethernal waiting. It is not bug but it is very disturbing event.

**Comment by HenrikAYT** [comment]
alright, thanks for the feedback!
